New folder/config/routes.rb
Rails.application.routes.draw do
  get 'shoot/subs'

  get 'delete/vome'
  get 'home/index'
  root 'home#index'

end

New folder/app/models/computer.rb
class Computer < ActiveRecord::Base
  validates_presence_of :used_at, :used_for , :allow_blank => false
  validates_length_of :cash, :maximum => 2000, :allow_blank => false
end

New folder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

New folder/app/controllers/delete_controller.rb
class DeleteController < ApplicationController
  def vome
  end
end

New folder/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

New folder/app/controllers/shoot_controller.rb
class ShootController < ApplicationController
  def subs
    useda = params[:Computer][:used_at]
    usedf = params[:Computer][:used_for]
    casha = params[:Computer][:cash]
    @pc = Computer.where("used_for = ? AND cash < ? AND used_at = ?",usedf ,casha , useda)
    render :subs
  end

end

New folder/app/helpers/application_helper.rb
module ApplicationHelper
end

New folder/app/helpers/delete_helper.rb
module DeleteHelper
end

New folder/app/helpers/home_helper.rb
module HomeHelper
end

New folder/app/helpers/shoot_helper.rb
module ShootHelper
end

New folder/app/views/delete/vome.html.erb
<div id="hi" class="section" data-is-active="true">
        <div class="hi-content">

            <h1 class="animated rotateInDownLeft"><span style="color:#E53A40;" class="nedim bold">Sqript</span>&nbsp;<span class="arabaci bold" style="color:#E53A40;" >Team</span></h1>

            <p>
                We're <span style="color:#E53A40;" class="develop bold">develop</span>ers who <span class="love bold" style="color:#E53A40;" >likes</span> to get our <span class="source bold" style="color:#E53A40;" >hands dirty!</span>
            </p>

            <div class="info animated bounceInRight" id="textgo">
                This is our first project.<span class="web-development bold" style="color:#E53A40;" >&nbsp; We're open</span>
                 to <span class="years bold" style="color:#E53A40;" >collaboration</span>.
                 <br/>Contact us @ <b style="color:#E53A40;">sqriptteam@outlook.com</b><br/>&nbsp;We're comprised of&nbsp;
                a <span class="frontend bold">designer</span>, <span class="backend bold">a front & back-end developer.</span> <br/>
                &nbsp;<br/><quote>"Design is not just what it looks like and feels like. Design is how it works."</quote><br/>
                <text> ~ Steve Jobs.
            </div>









          <%= link_to "Back to DiscoverPC", home_index_path, method: :get ,class: "take-a-look" %>














        </div>
</div>

New folder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="icon" type="image/png" href="favicon.ico.png">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Trouble finding the right computer? Answer a few Q's and you'll be on your way!">
  <meta name="author" content="SqriptTeam">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

New folder/app/views/shoot/subs.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<link rel='stylesheet' type='text/css' href='assets/stylesheets/shoot.scss' >
    <title>DiscoverPC | Results</title>
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/mdb.min.css" rel="stylesheet">

<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css'>
    <!-- Custom CSS -->
    <link href="css/stylish-portfolio.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet"/>
    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
html,
body,
header,
.view {
    height: 100%;
}
/* Navigation*/

/*Intro*/

.view {
    background: url("http://mdbootstrap.com/images/regular/nature/img%20(54).jpg")no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
</style>
</head>
<body>
  <header>

      <div class="view hm-black-strong">
          <div class="full-bg-img flex-center">
              <div class="container"  style="position:absolute; width:100%; height:50%; top:15%; left:15%;">
                      <div id="Done" class="container">  Here are the Computers Matching your search.   </div>
                  <div class="white-text text-xs-center wow fadeInUp " >
                    <table class="table table-bordered animate-table" id="ResultsTable">
                      <thead>
                        <tr>
                          <th>Computer</th>
                          <th>Price</th>
                          <th>Link</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @pc.each do |x| %>
                        <tr>
                          <td><%= x.name %></td>
                          <td>$<%= x.cash %></td>
                          <td><a href="<%= x.url %>" target="_blank"><b style="color:white; font-weight:bold;">Click me.</b></td>
                        </tr>
                        <% end %>
                <!-- -->

                      </tbody>
                    </table>

                      <br>

                  </div>

              </div>
          </div>
      </div>
      <!--/.Mask-->

  </header>
</body>